apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: marquez-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: secretstore-credential
    kind: SecretStore
  target:
    name: marquez-secret
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: MARQUEZ-DB-CREDENTIAL
